# Generated by Django 4.2.29 on 2026-03-25 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('views', models.IntegerField(default=0)),
                ('publish_time', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='news.category')),
            ],
            options={
                'ordering': ['-publish_time', '-id'],
                'indexes': [models.Index(fields=['category'], name='news_category_idx'), models.Index(fields=['publish_time'], name='news_publish_idx')],
            },
        ),
    ]
